

module.exports = [
"As you know, madness is like gravity...all it takes is a little push.",
"If you’re good at something, never do it for free.",
"Nobody panics when things go “according to plan”. Even if the plan is horrifying!",
"Do I really look like a guy with a plan? You know what I am? I'm a dog chasing cars. I wouldn't know what to do with one if I caught it! You know, I just... *do* things.",
"What doesn't kill you, simply makes you stranger!",
"Why so serious?",
"The only sensible way to live in this world is without rules.",
"Peace has cost you your strength! Victory has defeated you!",
"Theatricality and deception are powerful agents to the uninitiated... but we are initiated, aren't we Bruce?",
"You fight like a younger man, with nothing held back. Admirable but mistaken. ",
"Oh, you think darkness is your ally. But you merely adopted the dark; I was born in it, moulded by it. I didn't see the light until I was already a man, by then it was nothing to me but BLINDING! ",
"Ah, yes... I was wondering what would break first...Your spirit, or your body?",
"No one cared who I was until I put on the mask.",
"Speak of the devil and he shall appear.",
"Do you *feel* in charge? ",
"And this gives you *power* over me?",
"When a forest grows too wild, a purging fire is inevitable and natural.",
"You must become more than just a man in the mind of your opponent.",
"Justice is balance. You burned my house and left me for dead. Consider us even.",
"If someone stands in the way of true justice, you simply walk up behind them and stab them in the heart.",
"You haven't beaten me. You've sacrificed sure footing for a killing stroke. ",
"Your anger gives you great power. But if you let it, it will destroy you. As it almost did me",
"Say, That’s a Nice Bike",
    "I need your clothes, boots and your motorcycle.",
    "Do you want to know why I use a knife? Guns are too quick. You can’t savor all the… little emotions.",
    "Wendy? Darling? Light, of my life. I’m not gonna hurt ya. You didn’t let me finish my sentence. I said, I’m not gonna hurt ya. I’m just going to bash your brains in!",
    "And when his eyes go dead, the hell I sent him to must seem like heaven after what I’ve done to him.",
    "Don’t let yourself get attached to anything you are not willing to walk out on in 30 seconds flat if you feel the heat around the corner.",
    "What am I doing? I’m talking to a blank telephone, cause there is a dead man on the other end of this fucking line…",
    "You know how I stayed alive this long? All these years? Fear. The spectacle of fearsome acts.",
    "To protect the sheep you gotta catch the wolf, and it takes a wolf to catch a wolf.",
    "It’s not what you know, it’s what you can prove.",
    "I have all the characteristics of a human being: flesh, blood, skin, hair; but not a single, clear, identifiable emotion, except for greed and disgust.",
    "None of us really changes over time. We only become more fully what we are.",
    "I’ve seen things you people wouldn’t believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhäuser Gate. All those moments will be lost in time, like tears…in…rain. Time to die.",
    "My motto is if you want to win the lottery you’ve got to make money to get a ticket.",
    "Life is a game. So fight for survival and see if you’re worth it.",
    "And when Alexander saw the breadth of his domain, he wept, for there were no more worlds to conquer.",
    "I love rumors! Facts can be so misleading, where rumors, true or false, are often revealing.",
    "And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy My brothers. And you will know I am the Lord when I lay My vengeance upon you.",
    "All I have in this world is my balls and my word, and I don’t break them for no one.",
    "Become vengeance, David. Become wrath.",
    "The Korova Milk Bar sold milkplus, milk plus vellocet or synthemesc or drencrom, which is what we were drinking. This would sharpen you up and make you ready for a bit of the old ultra-violence.",
    "I gave you the chance of aiding me willingly, but you have elected the way of pain!",
    "If Mr. McMurphy doesn’t want to take his medication orally, I’m sure we can arrange that he can have it some other way. But I don’t think that he would like it.",
    "The fact that you've got 'Replica' written down the side of your gun. (withdraws his gun) And the fact that I've got 'Desert Eagle point five O' written on the side of mine, should precipitate your balls into shrinking, along with your presence.",
    "You should move to a small town, somewhere the rule of law still exists. You will not survive here. You are not a wolf, and this is a land of wolves now.",
    "You know what capitalism is? Getting fucked!",
    "I always tell tell the truth, even when i lie.",
    "So say good night to the bad guy!",
    "You are not special. You're not a beautiful and unique snowflake."
]